### ISSUE TITLE
recover original json from sexpdata dump

### ISSUE THREAD

**Issue by vanangamudi** [jd-boyd/sexpdata#52]
Original json record

#+begin_src python
  {'ExifTool:ExifToolVersion': 12.4,
   'File:ColumnCount': 91,
   'File:Delimiter': ',',
   'File:Directory': '/home/vanangamudi/ko-pa-ni',
   'File:FileAccessDate': '2023:12:18 13:32:27+05:30',
   'File:FileInodeChangeDate': '2023:12:16 15:04:02+05:30',
   'File:FileModifyDate': '2021:05:12 23:42:00+05:30',
   'File:FileName': 'exifinfo.csv',
   'File:FilePermissions': 100777,
   'File:FileSize': 34064,
   'File:FileType': 'CSV',
   'File:FileTypeExtension': 'CSV',
   'File:MIMEEncoding': 'us-ascii',
   'File:MIMEType': 'text/csv',
   'File:Newlines': '\n',
   'File:Quoting': '"',
   'File:RowCount': 73,
   'SourceFile': '/home/vanangamudi/ko-pa-ni/exifinfo.csv',
   '_id': ObjectId('658068a0b760ac3daf951f44')}
  #+end_src

#+begin_src lisp
  (:SourceFile "/home/vanangamudi/ko-pa-ni/exifinfo.csv"
               :ExifTool:ExifToolVersion 12.4
               :FileName "exifinfo.csv"
               :File:Directory "/home/vanangamudi/ko-pa-ni"
               :File:FileSize 34064
               :File:FileModifyDate "2021:05:12 23:42:00+05:30"
               :File:FileAccessDate "2023:12:18 13:32:27+05:30"
               :File:FileInodeChangeDate "2023:12:16 15:04:02+05:30"
               :File:FilePermissions 100777
               :File:FileType "CSV"
               :File:FileTypeExtension "CSV"
               :File:MIMEType "text/csv"
               :File:MIMEEncoding "us-ascii"
               :File:Newlines "\n"
               :File:Delimiter ","
               :File:Quoting "\""
               :File:ColumnCount 91
               :File:RowCount 73)
#+end_src

loaded data from sexpdata

#+begin_src python
  [Symbol(':SourceFile'), '/home/vanangamudi/ko-pa-ni/exifinfo.csv',
   Symbol(':ExifTool:ExifToolVersion'),  12.4,
   Symbol(':File:FileName'), 'exifinfo.csv',
   Symbol(':File:Directory'), '/home/vanangamudi/ko-pa-ni',
   Symbol(':File:FileSize'),   34064,
   Symbol(':File:FileModifyDate'),  '2021:05:12 23:42:00+05:30',
   Symbol(':File:FileAccessDate'),  '2023:12:18 13:32:27+05:30',
   Symbol(':File:FileInodeChangeDate'), '2023:12:16 15:04:02+05:30',
   Symbol(':File:FilePermissions'), 100777,
   Symbol(':File:FileType'),  'CSV',
   Symbol(':File:FileTypeExtension'),  'CSV',
   Symbol(':File:MIMEType'),  'text/csv',
   Symbol(':File:MIMEEncoding'), 'us-ascii',
   Symbol(':File:Newlines'),   '\n',
   Symbol(':File:Delimiter'),  ',',
   Symbol(':File:Quoting'),   '"',
   Symbol(':File:ColumnCount'),  91,
   Symbol(':File:RowCount'),  73]
#+end_src

I need to convert this into original json. is there a function already for this?

**Comment by jd-boyd** [comment]
There is an included `sexp2json.py` utility.  That hasn't been touched since 2012 it looks like, which was before I took over.   It fails on your example lisp data, which I think is a bug in the utility.  I will have to make a bug about that and either ditch that utility or modernize it.

That won't help you either.  The problem is that s-expressions don't natively have any equivalent of a dict data type.  I probably would have chosen to translate `{'a': 5, 'b': 6}` to `(("a" . 5) ("b" . 6))`, mirroring how a-lists are structured in common lisp and scheme, although even then they aren't really part of s-exps, they are functions that expect data in that list of pairs format.

For some reason implementing dicts into sexp formatted data the way that cl and scheme alist functions expect wasn't the choice by the original author 12+ years ago, and at this point I suspect that consumers of this library will depend on the current behavior.

It seems there is some call for better being able to customize with different personalities the way data is translated and formatting coming in and going out, but that should be a different issue (in fact there is one mentioning kicad). I'd be glad for someone to tackle, that, but I can't see doing it at the moment.
